Pyramid: Assign local object instead of temporary to vector
Using a temporary object causes strange error:
  error: no matching constructor for initialization
  note: candidate constructor not viable: expects an l-value for 1st argument

Vector implementation tries to convert value type to
reference type which is not possible using temporary
objects.

--HG--
extra : rebase_source : fd37c7e667fe9043d4faefb832a00d7d03469fad